### ISSUE TITLE
f4pga or fpga?

### ISSUE THREAD

**Issue by TheDHCreator** [SymbiFlow/f4pga-xc-fasm2bels#78]
Is the fasm2bels branch being called "f4pga-xc-fasm2bels" correct? Or is the "4" a spelling error?

Was just curious about it.

**Comment by mithro** [comment]
https://chipsalliance.org/announcement/2022/02/18/chips-alliance-forms-f4pga-workgroup-to-accelerate-adoption-of-open-source-fpga-tooling/

**Comment by TheDHCreator** [comment]
Okay! Thank you for clarifying.
